### ISSUE TITLE
Fire Pattern - Hard

### ISSUE THREAD

**Issue by lehmana** [OSU-CS361-W17/group3_project4#6]
This issue is to create the function that will handle what the computer does to fire at the user's ships when the game is on hard mode. This pattern will be to randomly fire at the board until a ship is found, then "search" around that space to try and find another ship square. Once the ship is completely sunk the computer will go back to firing at random.

**Comment by Swarles-Barkley** [comment]
Implemented searching around tiles with preference for tiles aligned with lines of 2 or more hits. (e.g. if {3,2} and {4,2} are hits, then computer will shoot at {2,2} and {5,2} before {3,3} or {4,1})
